package jmockit.demo;

/**
 * Hello world!
 *(generated by Maven Archetype)
 */
public class App 
{
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );
    }
}
